stages:
  - build

windows:
  # Use created image for mxe
  image: ffeldman/bionic-mxe-gcc9:latest
  stage: build
  # install the necessary build tools when needed
  before_script:
   #- apt update && apt -y install cmake libtiff5-dev #make autoconf g++ git cmake unzip
   #- apt -y install qtbase5-dev libcairo2-dev libtiff5-dev g++-8 sudo
  script:
 #   - git checkout windows
    - export PATH="/mxe/usr/bin:$PATH"
    - export PATH="/mxe/usr/x86_64-w64-mingw32.static/qt5/bin:$PATH"
    - export QT_SELECT=qt5

    # build gigamesh
    - mkdir build
    - cd build
    - /mxe/usr/bin/x86_64-w64-mingw32.static-cmake .. -DCMAKE_BUILD_TYPE=Release -G"Unix Makefiles"
    - /mxe/usr/bin/x86_64-w64-mingw32.static-make -j
    - cd ..

  artifacts:
    name: "gigamesh_windows"
    paths:
      - build/gui/gigamesh.exe
      - build/clt/gigamesh-featurevectors.exe
      - build/clt/gigamesh-tolegacy.exe
      - build/clt/gigamesh-clean.exe
      - build/clt/gigamesh-info.exe
      - build/clt/gigamesh-borders.exe
    expire_in: 4 hours
   
ubuntu bionic:
  # Use ubuntu 18.04 LTS
  image: ubuntu:bionic
  stage: build
  # install the necessary build tools when needed
  before_script: 
   - apt update && apt -y install make autoconf g++ git cmake unzip
   - apt -y install qtbase5-dev libcairo2-dev libtiff5-dev g++-8 sudo
  script:
    # Make sure g++-8, gcc-8 is default
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 10
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 10
    - export QT_SELECT=qt5

    # build gigamesh
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -G"Unix Makefiles"
    - make -j
    - cd ..

  artifacts:
    name: "gigamesh_bionic"
    paths:
      - build/gui/gigamesh
      - build/clt/gigamesh-featurevectors
      - build/clt/gigamesh-tolegacy
      - build/clt/gigamesh-clean
      - build/clt/gigamesh-info
      - build/clt/gigamesh-borders
    expire_in: 4 hours
    
manjaro arch:
  # Use latest manjaro release
  image: archlinux/base
  stage: build
  # install the necessary build tools when needed
  before_script: 
   - pacman -Sy
   - pacman -S gcc glibc cmake boost unzip qtcreator make cairo git --noconfirm
  script:
    - export QT_SELECT=qt5

    # build gigamesh
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -G"Unix Makefiles"
    - make -j
    - cd ..

  artifacts:
    name: "gigamesh_arch_manjaro"
    paths:
      - build/gui/gigamesh
      - build/clt/gigamesh-featurevectors
      - build/clt/gigamesh-tolegacy
      - build/clt/gigamesh-clean
      - build/clt/gigamesh-info
      - build/clt/gigamesh-borders
    expire_in: 4 hours
  
